### ISSUE TITLE
panic: `slice index starts at X but ends at Y`

### ISSUE THREAD

**Issue by langston-barrett** [langston-barrett/tree-crasher#21]
```
thread '<unnamed>' panicked at 'slice index starts at 984 but ends at 78', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-edit-0.1.2/src/print.rs:40:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: core::slice::index::slice_index_order_fail_rt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/slice/index.rs:99:5
   3: core::slice::index::slice_index_order_fail
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/slice/index.rs:92:14
   4: tree_sitter_edit::print::render
   5: treereduce::reduce::Ctx<T>::interesting
   6: treereduce::reduce::work
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'Thread panic'd!: Any { .. }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/treereduce-0.2.1/src/reduce.rs:595:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/result.rs:1790:5
   3: treereduce::reduce::treereduce_multi_pass
   4: tree_crasher::job
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by langston-barrett** [comment]
Looks like `merge_edits` has a precondition that its inputs are sorted according to start position:

https://github.com/langston-barrett/tree-sitter-edit/blob/97118adb52cd0d52776096618667a31a58de3daf/src/print.rs#L37-L46

This was probably the case before this commit:

https://github.com/langston-barrett/tree-sitter-edit/commit/80546f4eb3d3d90b3227e75b731d3f8e8a5313ba

**Comment by langston-barrett** [comment]
Will be fixed in the next bump of tree-splicer.
